# Generated by Django 5.2.3 on 2025-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_debt_amount_payment_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='примечание'),
        ),
    ]
