# Generated by Django 5.2.3 on 2025-07-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_debt_created_by_debt_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.membership'),
        ),
    ]
