# Generated by Django 5.2.3 on 2025-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_debt_options_alter_payment_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='freeze_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='freeze_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
